********************************
Input Arguments
Gene Annotation and Expression file: /Users/rebeccayu/Projects/TIGAR/ExampleData/gene_exp.txt
Training sampleID file: /Users/rebeccayu/Projects/TIGAR/ExampleData/sampleID.txt
Chromosome: 1
Training genotype file: /Users/rebeccayu/Projects/TIGAR/ExampleData/example.vcf.gz
Genotype file used for training is type: vcf
Genotype data format: GT
Gene training region SNP inclusion window: +-1000000
Excluding SNPs if missing rate exceeds: 0.2
MAF threshold for SNP inclusion: 0.01
HWE p-value threshold for SNP inclusion: 0.0001
Evaluating DPR model by 5-fold cross validation with inclusion threshold Avg.CVR2 >0.005.
DPR model: 1 - Variational Bayesian
Output Effect-size type: fixed
Number of threads: 2
Output directory: /Users/rebeccayu/Projects/TIGAR/ExampleData/output/DPR_CHR1
Output training weights file: /Users/rebeccayu/Projects/TIGAR/ExampleData/output/DPR_CHR1/temp_CHR1_DPR_train_eQTLweights.txt
Output training info file: /Users/rebeccayu/Projects/TIGAR/ExampleData/output/DPR_CHR1/CHR1_DPR_train_GeneInfo.txt
********************************
Reading genotype, expression file headers, sample IDs.

Reading sampleID file.

Reading file headers.

Matching sampleIDs.

Running job for 129 matched sampleIDs.
Reading gene expression data.

Splitting sample IDs randomly for 5-fold cross validation by average R2...

Creating file: /Users/rebeccayu/Projects/TIGAR/ExampleData/output/DPR_CHR1/temp_CHR1_DPR_train_eQTLweights.txt

Creating file: /Users/rebeccayu/Projects/TIGAR/ExampleData/output/DPR_CHR1/CHR1_DPR_train_GeneInfo.txt

********************************

Starting DPR training for 4 target genes.

num=0
TargetID=ENSG00000223972.4
Running 5-fold CV.
Caught an exception for num=0:
  OSError: [Errno 8] Exec format error
Traceback:
  File "/Users/rebeccayu/Projects/TIGAR/Model_Train_Pred/DPR_Train.py", line 360, in thread_process
    avg_r2_cv = do_cv(target, Bimbam, Pheno, BimbamC, PhenoC, CV_train_test_ID)
  File "/Users/rebeccayu/Projects/TIGAR/Model_Train_Pred/DPR_Train.py", line 196, in do_cv
    target_cv)[['snpID','ES']]
  File "/Users/rebeccayu/Projects/TIGAR/Model_Train_Pred/DPR_Train.py", line 129, in prep_call_dpr
    stdout=subprocess.DEVNULL)
  File "/opt/anaconda3/envs/tigarenv/lib/python3.5/subprocess.py", line 266, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/opt/anaconda3/envs/tigarenv/lib/python3.5/subprocess.py", line 247, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/anaconda3/envs/tigarenv/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/opt/anaconda3/envs/tigarenv/lib/python3.5/subprocess.py", line 1289, in _execute_child
    raise child_exception_type(errno_num, err_msg)

num=1
TargetID=ENSG00000227232.4
Running 5-fold CV.
Caught an exception for num=1:
  OSError: [Errno 8] Exec format error
Traceback:
  File "/Users/rebeccayu/Projects/TIGAR/Model_Train_Pred/DPR_Train.py", line 360, in thread_process
    avg_r2_cv = do_cv(target, Bimbam, Pheno, BimbamC, PhenoC, CV_train_test_ID)
  File "/Users/rebeccayu/Projects/TIGAR/Model_Train_Pred/DPR_Train.py", line 196, in do_cv
    target_cv)[['snpID','ES']]
  File "/Users/rebeccayu/Projects/TIGAR/Model_Train_Pred/DPR_Train.py", line 129, in prep_call_dpr
    stdout=subprocess.DEVNULL)
  File "/opt/anaconda3/envs/tigarenv/lib/python3.5/subprocess.py", line 266, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/opt/anaconda3/envs/tigarenv/lib/python3.5/subprocess.py", line 247, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/anaconda3/envs/tigarenv/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/opt/anaconda3/envs/tigarenv/lib/python3.5/subprocess.py", line 1289, in _execute_child
    raise child_exception_type(errno_num, err_msg)

num=2
TargetID=ENSG00000237613.2
Running 5-fold CV.
Caught an exception for num=2:
  OSError: [Errno 8] Exec format error
Traceback:
  File "/Users/rebeccayu/Projects/TIGAR/Model_Train_Pred/DPR_Train.py", line 360, in thread_process
    avg_r2_cv = do_cv(target, Bimbam, Pheno, BimbamC, PhenoC, CV_train_test_ID)
  File "/Users/rebeccayu/Projects/TIGAR/Model_Train_Pred/DPR_Train.py", line 196, in do_cv
    target_cv)[['snpID','ES']]
  File "/Users/rebeccayu/Projects/TIGAR/Model_Train_Pred/DPR_Train.py", line 129, in prep_call_dpr
    stdout=subprocess.DEVNULL)
  File "/opt/anaconda3/envs/tigarenv/lib/python3.5/subprocess.py", line 266, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/opt/anaconda3/envs/tigarenv/lib/python3.5/subprocess.py", line 247, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/anaconda3/envs/tigarenv/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/opt/anaconda3/envs/tigarenv/lib/python3.5/subprocess.py", line 1289, in _execute_child
    raise child_exception_type(errno_num, err_msg)

num=3
TargetID=ENSG00000243485.2
Running 5-fold CV.
Caught an exception for num=3:
  OSError: [Errno 8] Exec format error
Traceback:
  File "/Users/rebeccayu/Projects/TIGAR/Model_Train_Pred/DPR_Train.py", line 360, in thread_process
    avg_r2_cv = do_cv(target, Bimbam, Pheno, BimbamC, PhenoC, CV_train_test_ID)
  File "/Users/rebeccayu/Projects/TIGAR/Model_Train_Pred/DPR_Train.py", line 196, in do_cv
    target_cv)[['snpID','ES']]
  File "/Users/rebeccayu/Projects/TIGAR/Model_Train_Pred/DPR_Train.py", line 129, in prep_call_dpr
    stdout=subprocess.DEVNULL)
  File "/opt/anaconda3/envs/tigarenv/lib/python3.5/subprocess.py", line 266, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/opt/anaconda3/envs/tigarenv/lib/python3.5/subprocess.py", line 247, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/anaconda3/envs/tigarenv/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/opt/anaconda3/envs/tigarenv/lib/python3.5/subprocess.py", line 1289, in _execute_child
    raise child_exception_type(errno_num, err_msg)

Done.
Computation time (DD:HH:MM:SS): 00:00:00:03
